export interface QuestionnaireFormData {
  name: string;
  businessName: string;
  city: string;
  whatYouDo: string;
  industry: string;
  brandType: string;
  personalStory: string;
  industryAnswers: Record<string, string>;
  onCameraPersonality: string[];
  contentEnjoyed: string[];
  daysToPost: number;
  primaryGoal: string;
  antiBrandWords: string;
  contentSample: string;
  signaturePhrases: string;
  brandWords: string;
  currentOffer: string;
  preferredCTA: string;
  speakingStyle: string;
  humorStyle: string;
  sentenceLength: string;
  audienceLabel: string;
  clientWords: string;
  contentBoundaries: string;
  familyContext: string;
  morningRoutine: string;
  hotTakes: string;
  emojiUsage: string;
  formattingStyle: string;
  storytellingStyle: string;
}
